=== nathczo/projetxml/tree.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="tree">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="node" type="Node" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Node">
        <xsd:sequence>
            <xsd:element name="child" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="idref" type="xsd:IDREF" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID" use="required"/>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>


</xsd:schema>

=== nathczo/projetxml/transformations/petitxml.xml
<?xml version="1.0" encoding="utf-8"?>
<tree
	xsi:noNamespaceSchemaLocation="tree.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<node id="id1" name="Life on Earth">
		<child idref="id2"/>
		<child idref="id3"/>
		<child idref="id4"/>
	</node>
	<node id="id2" name="Eubacteria">
		<child idref="id5"/>
		<child idref="id6"/>
	</node>
	<node id="id3" name="Aquificae">
	</node>
	<node id="id4" name="Life on Earth">
		<child idref="id7"/>
		<child idref="id8"/>
	</node>
	<node id="id5" name="Eubacteria">
	</node>
	<node id="id6" name="Aquificae">
		<child idref="id9"/>
		<child idref="id10"/>
	</node>
	<node id="id7" name="Life on Earth">
	</node>
	<node id="id8" name="Eubacteria">
	</node>
	<node id="id9" name="Aquificae">
	</node>
	<node id="id10" name="Aquificae">
	</node>
</tree>
